apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.fullname" . }}
  labels:
    {{- include "synapse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: {{ .Values.service.replication.port }}
      targetPort: replication
      protocol: TCP
      name: replication
  selector:
    {{- include "synapse.selectorLabels" . | nindent 4 }}
